#!/bin/bash
#PBS -l nodes=1:ppn=8,vmem=15gb,walltime=48:00:00
#PBS -N bl.freesurfer

set -e
set -x

[ -z "$FREESURFER_LICENSE" ] && echo "Please set FREESURFER_LICENSE in .bashrc" && exit 1;
echo $FREESURFER_LICENSE > license.txt

#-hippocampal-subfields-T1t2 requires matlab binary to run on freeesurfer_on_mcr
time singularity exec -e -B `pwd`/license.txt:/usr/local/freesurfer/license.txt \
	docker://brainlife/freesurfer_on_mcr:6.0.2 ./freesurfer.sh


