#!/bin/bash
#PBS -l nodes=1:ppn=8,vmem=15gb,walltime=24:00:00
#PBS -N bl.freesurfer

set -e
set -x

[ -z "$FREESURFER_LICENSE" ] && echo "Please set FREESURFER_LICENSE in .bashrc" && exit 1;
echo $FREESURFER_LICENSE > license.txt

#-hippocampal-subfields-T1t2 requires matlab binary to run on freeesurfer_on_mcr
version=$(jq -r .version config.json)
case $version in
6.0.0)
    container="brainlife/freesurfer_on_mcr:6.0.0"
    ;;
6.0.1)
    container="brainlife/freesurfer:6.0.1"
    ;;
7.0.0)
    container="brainlife/freesurfer:7.0.0"
    ;;
7.1.0)
    container="brainlife/freesurfer:7.1.0"
    ;;
dev)
    container="brainlife/freesurfer:dev"
    ;;
*)
    echo "unknown version:$version.. using the latest brainlife/freesurfer"
    container="brainlife/freesurfer"
    ;;
esac

time singularity exec -e -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://$container ./freesurfer.sh


